runtime: nodejs20
service: notes-shofi

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1

handlers:
  # Handler untuk file script.js (karena dia ada di root folder fe)
  - url: /script.js
    static_files: script.js
    upload: script.js

  # Handler untuk file style (sesuaikan namanya, misal style.css)
  - url: /style.css
    static_files: style.css
    upload: style.css

  # Handler utama untuk index.html
  - url: /.*
    static_files: main.html
    upload: main.html