# API Testing
GET http://localhost:3000/ HTTP/1.1

###
# GET : All Notes
GET http://localhost:3000/api/v1/notes HTTP/1.1
Content-Type: application/json

###
# GET : Note by ID
GET http://localhost:3000/api/v1/notes/3 HTTP/1.1
Content-Type: application/json

###
# POST : Create Note
POST http://localhost:3000/api/v1/notes HTTP/1.1
Content-Type: application/json

{
  "judul": "Ini udah di gcp",
  "isi": "Test apakah masuk ke cloud sql?"
}

###
# PUT : Update Note
PUT http://localhost:3000/api/v1/notes/3 HTTP/1.1
Content-Type: application/json

{
  "judul": "Coba update catatan",
  "isi": "Ini hari senin pukul 4 sore"
}

###
# DELETE : Delete Note
DELETE http://localhost:3000/api/v1/notes/3 HTTP/1.1
Content-Type: application/json


